name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android/src
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4 # Обновили до v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Java 17 более стабильна для старых версий Gradle

      - name: Change wrapper permissions
        run: chmod +x gradlew # Гарантируем, что скрипт можно запустить

      - name: Build with Gradle
        run: ./gradlew assembleDebug # Debug собирается быстрее и проще для проверки
